### PR TITLE
[WIP] Updates to how you create migrations, middleware auto injected, folde…

### PR DESCRIPTION
**Pull request by lukepolo**
This is WIP

Ideas : 

- [x] Column set on user to define what version of api to use
- [x] Cache versions when using php artisan cache , or cache right away?
- [x] Migrations command interactive to choose version and create versions
- [x] Provide Full path instead of just paths , allows usage to use route helpers
- [ ] API Versioning , if releasing a new major version these migrations will be invalid 

image

image

Let me know on your thoughts~

### CODE REVIEW

**Comment by sixlive** [comment]
Few opinions:

* I would stay away from forcing a 'date' construct to the versioning, might want to use some other paradigm to version with
* I'm not sure how I feel about forcing version pinning out of the box in the DB (storing the version on the user record)

**Comment by jbrooksuk** [comment]
Also, auto-injecting the middleware is a no-no from me.

**Comment by lukepolo** [comment]
The pinning is what Stripe does, makes it a bit easier on the end user , could always make it optional.

**Comment by lukepolo** [comment]
Curious about the auto injecting? You'll need it to use the package. You can always use your own service provider to remove it if you want to write your own.

**Comment by lukepolo** [comment]
Will remove the date enforcement , let them choose how to use it

**Comment by sixlive** [comment]
I agree with @jbrooksuk on auto binding middleware.

I know pinning is what stripe does but I'm wary of how many assumptions it will make about your user constructs. I guess if you build it in such a way that it interacts with `Authenticatable` then it shouldn't be too bad, but would absolutely make it optional.

**Comment by lukepolo** [comment]
@jbrooksuk @sixlive I had to agree in the end with auto injecting, it just doesn't allow for more freedom to put it where you need it

**Comment by lukepolo** [comment]
Talked with the creator, moving in different directions for convention over configuration

**Pull request closed without merging**
