### PR TITLE
Uses Symfony Response

### PR DESCRIPTION
**Pull request by sixlive**
Switched to Sympfony reponse so that a wider varity of responses
can be accepted.

### CODE REVIEW

**Comment by sixlive** [comment]
@tomschlick should we also update the RequestMigration class? https://github.com/tomschlick/request-migrations/blob/5e94bd2abe2e1881afdd039d3c729085ef0372b9/src/RequestMigration.php#L26

**Comment by tomschlick** [comment]
Yeah probably. Also should we be using the interface not the direct class?

**Comment by sixlive** [comment]
Whoops! Yeah, that's what I meant!

Edit: Yeah, there isn't really an Interface...

**Comment by sixlive** [comment]
@tomschlick should be all set now. I can squash these commits together if you prefer.

**Comment by tomschlick** [comment]
Nope, github does that for us. Merging now 👍

**Pull request merged**
